// QuantRadar CLI: discovery, screening, scanning and backtesting.
use anyhow::{Context,Result};
use chrono::Utc;
use clap::{Parser,Subcommand};
use futures::stream::{FuturesUnordered,StreamExt};
use quantaradar_backtest::{run as backtest,BacktestConfig};
use quantaradar_core::{Bar,ScreenResult};
use quantaradar_exchange_kraken::KrakenClient;
use quantaradar_features::feature_rows;
use quantaradar_regime::{classify,RegimeThresholds};
use quantaradar_reporting::write_json;
use quantaradar_screeners::run_default;
use std::{fs,path::PathBuf,sync::Arc};
use tokio::sync::Semaphore;
#[derive(Parser,Debug)]#[command(name="quantaradar",version,about="Market intelligence and quantitative research platform")]
struct Cli{#[command(subcommand)]command:Command}
#[derive(Subcommand,Debug)]enum Command{Discover{#[arg(long,default_value="reports/markets.json")]out:PathBuf},Scan{#[arg(long,default_value_t=1440)]interval:u32,#[arg(long,default_value_t=50)]limit:usize,#[arg(long,default_value_t=8)]concurrency:usize,#[arg(long,default_value="USD")]quote:String,#[arg(long,default_value="reports/scan.json")]out:PathBuf},Fetch{pair:String,#[arg(long,default_value_t=1440)]interval:u32,#[arg(long,default_value="data/raw")]out_dir:PathBuf},Screen{pair:String,#[arg(long,default_value_t=1440)]interval:u32,#[arg(long,default_value="reports/screen.json")]out:PathBuf},Backtest{file:PathBuf,#[arg(long,default_value="reports/backtest.json")]out:PathBuf,#[arg(long,default_value_t=10_000.0)]cash:f64}}
#[tokio::main]async fn main()->Result<()>{tracing_subscriber::fmt().with_env_filter("info").init();match Cli::parse().command{Command::Discover{out}=>{let markets=KrakenClient::default().discover_spot().await?;write_json(&out,&markets)?;println!("discovered {} markets",markets.len());},Command::Scan{interval,limit,concurrency,quote,out}=>{let c=KrakenClient::default();let markets=c.discover_spot().await?;let selected:Vec<_>=markets.into_iter().filter(|m|m.quote.eq_ignore_ascii_case(&quote)||m.quote.ends_with(&quote)).take(limit).collect();let sem=Arc::new(Semaphore::new(concurrency.max(1)));let mut jobs=FuturesUnordered::new();for m in selected{let permit=sem.clone().acquire_owned().await?;let client=c.clone();jobs.push(tokio::spawn(async move{let _permit=permit;let symbol=if m.symbol.is_empty(){m.base.clone()}else{m.symbol.clone()};let bars=client.ohlc(&symbol,interval).await;(symbol,bars)}));}let mut signals=Vec::new();while let Some(j)=jobs.next().await{let(symbol,bars)=j?;if let Ok(bars)=bars{let rows=feature_rows(&symbol,&bars);if let Some(last)=rows.last(){let regime=classify(last,RegimeThresholds::default());signals.extend(run_default(&rows,regime));}}}signals.sort_by(|a,b|b.score.total_cmp(&a.score));let result=ScreenResult{generated_at:Utc::now(),regime:quantaradar_core::Regime::Unknown,signals};write_json(&out,&result)?;println!("{}",serde_json::to_string_pretty(&result)?);},Command::Fetch{pair,interval,out_dir}=>{let bars=KrakenClient::default().ohlc(&pair,interval).await?;fs::create_dir_all(&out_dir)?;let path=out_dir.join(format!("{}.json",pair.replace('/','_')));write_json(&path,&bars)?;println!("wrote {} bars to {}",bars.len(),path.display());},Command::Screen{pair,interval,out}=>{let bars=KrakenClient::default().ohlc(&pair,interval).await?;let rows=feature_rows(&pair,&bars);let last=rows.last().context("not enough market data")?;let regime=classify(last,RegimeThresholds::default());let result=ScreenResult{generated_at:Utc::now(),regime:regime.clone(),signals:run_default(&rows,regime)};write_json(&out,&result)?;println!("{}",serde_json::to_string_pretty(&result)?);},Command::Backtest{file,out,cash}=>{let bars:Vec<Bar>=serde_json::from_slice(&fs::read(&file)?)?;let result=backtest(&bars,&BacktestConfig{initial_cash:cash,..Default::default()});write_json(&out,&result)?;println!("{}",serde_json::to_string_pretty(&result)?);}}Ok(())}
