// Deterministic technical indicators. No network or global mutable state.
use quantaradar_core::{safe_return, Bar, FeatureRow};

pub fn ema(values: &[f64], period: usize) -> Vec<Option<f64>> { let mut out=vec![None;values.len()]; if period==0||values.len()<period{return out;} let k=2.0/(period as f64+1.0); let mut prev=values[..period].iter().sum::<f64>()/period as f64; out[period-1]=Some(prev); for i in period..values.len(){prev=values[i]*k+prev*(1.0-k);out[i]=Some(prev);}out }
pub fn rsi(values:&[f64],period:usize)->Vec<Option<f64>>{let mut out=vec![None;values.len()];if period==0||values.len()<=period{return out;}let mut gains=0.0;let mut losses=0.0;for i in 1..=period{let d=values[i]-values[i-1];if d>=0.0{gains+=d}else{losses-=d}}let mut ag=gains/period as f64;let mut al=losses/period as f64;out[period]=Some(rsi_value(ag,al));for i in period+1..values.len(){let d=values[i]-values[i-1];let g=d.max(0.0);let l=(-d).max(0.0);ag=(ag*(period as f64-1.0)+g)/period as f64;al=(al*(period as f64-1.0)+l)/period as f64;out[i]=Some(rsi_value(ag,al));}out}
fn rsi_value(g:f64,l:f64)->f64{if l<=f64::EPSILON{100.0}else{100.0-100.0/(1.0+g/l)}}
pub fn atr(bars:&[Bar],period:usize)->Vec<Option<f64>>{let mut tr=vec![0.0;bars.len()];for i in 0..bars.len(){tr[i]=if i==0{bars[i].high-bars[i].low}else{(bars[i].high-bars[i].low).max((bars[i].high-bars[i-1].close).abs()).max((bars[i].low-bars[i-1].close).abs())}}let mut out=vec![None;bars.len()];if period==0||bars.len()<period{return out;}let mut a=tr[..period].iter().sum::<f64>()/period as f64;out[period-1]=Some(a);for i in period..bars.len(){a=(a*(period as f64-1.0)+tr[i])/period as f64;out[i]=Some(a)}out}
pub fn rolling_std(values:&[f64],period:usize,i:usize)->Option<f64>{if i+1<period{return None}let s=&values[i+1-period..=i];let m=s.iter().sum::<f64>()/period as f64;Some((s.iter().map(|x|(x-m).powi(2)).sum::<f64>()/period as f64).sqrt())}
pub fn feature_rows(symbol:&str,bars:&[Bar])->Vec<FeatureRow>{let closes:Vec<f64>=bars.iter().map(|b|b.close).collect();let volumes:Vec<f64>=bars.iter().map(|b|b.volume).collect();let e20=ema(&closes,20);let e50=ema(&closes,50);let e200=ema(&closes,200);let rs=rsi(&closes,14);let at=atr(bars,14);bars.iter().enumerate().map(|(i,b)|{let ret=|lag:usize|i.checked_sub(lag).and_then(|j|safe_return(closes[i],closes[j]));let rv=if i>=20{let x=(i-19..=i).map(|j|ret(1).unwrap_or(0.0)).collect::<Vec<_>>();Some(x.iter().map(|v|v*v).sum::<f64>().sqrt())}else{None};let width=rolling_std(&closes,20,i).map(|s|4.0*s/closes[i]);let vz=if i>=20{let s=&volumes[i-20..i];let m=s.iter().sum::<f64>()/s.len() as f64;let sd=(s.iter().map(|x|(x-m).powi(2)).sum::<f64>()/s.len() as f64).sqrt();Some((volumes[i]-m)/sd.max(1e-12))}else{None};let dist=e20[i].zip(at[i]).map(|(e,a)|(closes[i]-e)/a.max(1e-12));let high=i>=20&&closes[i]>closes[i-20..i].iter().copied().fold(f64::NEG_INFINITY,f64::max);let low=i>=20&&closes[i]<closes[i-20..i].iter().copied().fold(f64::INFINITY,f64::min);FeatureRow{ts:b.ts,symbol:symbol.to_string(),close:b.close,returns_1:ret(1),returns_4:ret(4),returns_24:ret(24),returns_72:ret(72),ema_20:e20[i],ema_50:e50[i],ema_200:e200[i],rsi_14:rs[i],atr_14:at[i],atr_pct:at[i].map(|v|v/b.close),realized_vol_20:rv,bb_width_20:width,volume_z_20:vz,distance_ema20_atr:dist,breakout_20:high,new_high_20:high,new_low_20:low}}).collect()}
