// Cost-aware deterministic event-driven backtester.
use chrono::{DateTime,Utc};
use quantaradar_core::Bar;
use serde::{Deserialize,Serialize};
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct BacktestConfig{pub initial_cash:f64,pub fee_bps:f64,pub slippage_bps:f64,pub fast:usize,pub slow:usize}
impl Default for BacktestConfig{fn default()->Self{Self{initial_cash:10_000.0,fee_bps:8.0,slippage_bps:3.0,fast:20,slow:50}}}
#[derive(Debug,Clone,Serialize,Deserialize)]pub struct BacktestResult{pub initial_cash:f64,pub final_cash:f64,pub total_return:f64,pub max_drawdown:f64,pub trades:usize,pub win_rate:f64,pub equity:Vec<(DateTime<Utc>,f64)>}
fn sma(xs:&[f64],p:usize)->Option<f64>{if xs.len()<p{None}else{Some(xs[xs.len()-p..].iter().sum::<f64>()/p as f64)}}
pub fn run(bars:&[Bar],c:&BacktestConfig)->BacktestResult{let mut cash=c.initial_cash;let mut qty=0.0;let mut peak=c.initial_cash;let mut max_dd=0.0;let mut entry=0.0;let(mut wins,mut trades)=(0usize,0usize);let mut eq=Vec::with_capacity(bars.len());let closes:Vec<f64>=bars.iter().map(|b|b.close).collect();for i in 0..bars.len(){let fast=sma(&closes[..=i],c.fast);let slow=sma(&closes[..=i],c.slow);let price=bars[i].close;let long=fast.zip(slow).map(|(a,b)|a>b).unwrap_or(false);if long&&qty==0.0{let px=price*(1.0+c.slippage_bps/10_000.0);let fee=c.fee_bps/10_000.0;qty=(cash/(px*(1.0+fee))).max(0.0);cash-=qty*px*(1.0+fee);entry=px;trades+=1;}else if !long&&qty>0.0{let px=price*(1.0-c.slippage_bps/10_000.0);let fee=c.fee_bps/10_000.0;cash+=qty*px*(1.0-fee);if px>entry{wins+=1}qty=0.0;}let equity=cash+qty*price;peak=peak.max(equity);max_dd=max_dd.max((peak-equity)/peak.max(1.0));eq.push((bars[i].ts,equity));}if qty>0.0{let price=*closes.last().unwrap_or(&0.0);cash+=qty*price*(1.0-c.fee_bps/10_000.0);}BacktestResult{initial_cash:c.initial_cash,final_cash:cash,total_return:cash/c.initial_cash-1.0,max_drawdown:max_dd,trades,win_rate:if trades==0{0.0}else{wins as f64/trades as f64},equity:eq}}
